#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)
cd "$ROOT_DIR"

cargo test -p pg_gateway --lib

PG_GATEWAY_POSTGRES_SMOKE_REQUIRE_ALL="${PG_GATEWAY_POSTGRES_SMOKE_REQUIRE_ALL:-1}" \
PG_GATEWAY_POSTGRES_SMOKE_WITH_PYTHON="${PG_GATEWAY_POSTGRES_SMOKE_WITH_PYTHON:-1}" \
PG_GATEWAY_POSTGRES_SMOKE_WITH_SQLX="${PG_GATEWAY_POSTGRES_SMOKE_WITH_SQLX:-1}" \
PG_GATEWAY_POSTGRES_SMOKE_WITH_JDBC="${PG_GATEWAY_POSTGRES_SMOKE_WITH_JDBC:-1}" \
PG_GATEWAY_POSTGRES_SMOKE_WITH_PGBENCH="${PG_GATEWAY_POSTGRES_SMOKE_WITH_PGBENCH:-1}" \
pg_gateway/tests/postgres_smoke/run.sh
